// Mocks generated by Mockito 5.4.6 from annotations
// in ferna/test/providers/plant_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:ferna/models/plant.dart' as _i2;
import 'package:ferna/services/plant_service.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePlant_0 extends _i1.SmartFake implements _i2.Plant {
  _FakePlant_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PlantService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPlantService extends _i1.Mock implements _i3.PlantService {
  MockPlantService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.Plant>> getUserPlants({
    int? limit = 20,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getUserPlants, [], {
              #limit: limit,
              #offset: offset,
            }),
            returnValue: _i4.Future<List<_i2.Plant>>.value(<_i2.Plant>[]),
          )
          as _i4.Future<List<_i2.Plant>>);

  @override
  _i4.Future<_i2.Plant?> getPlant(int? plantId) =>
      (super.noSuchMethod(
            Invocation.method(#getPlant, [plantId]),
            returnValue: _i4.Future<_i2.Plant?>.value(),
          )
          as _i4.Future<_i2.Plant?>);

  @override
  _i4.Future<_i2.Plant> createPlant({
    required int? speciesId,
    String? nickname,
    String? imageUrl,
    int? wateringFrequencyDays,
    DateTime? lastWateredAt,
    String? note,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createPlant, [], {
              #speciesId: speciesId,
              #nickname: nickname,
              #imageUrl: imageUrl,
              #wateringFrequencyDays: wateringFrequencyDays,
              #lastWateredAt: lastWateredAt,
              #note: note,
            }),
            returnValue: _i4.Future<_i2.Plant>.value(
              _FakePlant_0(
                this,
                Invocation.method(#createPlant, [], {
                  #speciesId: speciesId,
                  #nickname: nickname,
                  #imageUrl: imageUrl,
                  #wateringFrequencyDays: wateringFrequencyDays,
                  #lastWateredAt: lastWateredAt,
                  #note: note,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.Plant>);

  @override
  _i4.Future<_i2.Plant> updatePlant({
    required int? plantId,
    int? speciesId,
    String? nickname,
    String? imageUrl,
    int? wateringFrequencyDays,
    DateTime? lastWateredAt,
    String? note,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updatePlant, [], {
              #plantId: plantId,
              #speciesId: speciesId,
              #nickname: nickname,
              #imageUrl: imageUrl,
              #wateringFrequencyDays: wateringFrequencyDays,
              #lastWateredAt: lastWateredAt,
              #note: note,
            }),
            returnValue: _i4.Future<_i2.Plant>.value(
              _FakePlant_0(
                this,
                Invocation.method(#updatePlant, [], {
                  #plantId: plantId,
                  #speciesId: speciesId,
                  #nickname: nickname,
                  #imageUrl: imageUrl,
                  #wateringFrequencyDays: wateringFrequencyDays,
                  #lastWateredAt: lastWateredAt,
                  #note: note,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.Plant>);

  @override
  _i4.Future<void> deletePlant(int? plantId) =>
      (super.noSuchMethod(
            Invocation.method(#deletePlant, [plantId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
